[package]
name = "tcx-eth"
version = "0.1.0"
authors = ["Neal Xu <imxuneal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcx-crypto = { path = "../tcx-crypto" }
tcx-chain = { path = "../tcx-chain" }
tcx-primitive = { path = "../tcx-primitive" }
tcx-constants = { path = "../tcx-constants" }

rlp = "0.4.5"
num-bigint = "0.2.6"
tiny-keccak = "1.4"
libsecp256k1 = "0.3.5"

regex = "1"

hex = "0.3.2"
#base64 = "0.10.1"

#bitcoin = "0.21.0"
#secp256k1 = {version ="0.15", features = ["recovery"] }
#tiny-bip39 = "0.6.2"
#bitcoin_hashes = "0.7"
#bitcoinconsensus = { version = "0.16", optional = true }
#serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0.39"
#uuid = { version = "0.7", features = ["serde", "v4"] }
failure = "0.1.5"
#num-traits = "0.2"
#num-integer = "0.1"
byteorder = "1.3.2"
prost = "0.5.0"
bytes = "0.4.12"
prost-types = "0.5.0"